### PR TITLE
rmarkdown template to fit with blog format

### PR DESCRIPTION
**Pull request by joebrew**
@xingcbrew and @benmbrew I've tagged both of you to review this.

@benmbrew For your review, please both check correctness of code AND try to generate (locally only) a blog post based on `template.Rmd`, so as to make sure that everything works.

@xingcbrew For your review, can you just go over the html in `post_template.html` and make sure everything looks right to you? Note that there are some "variables" (as denoted by `$...$`) where the rmarkdown stuff comes in...

Let me know if you have any questions. I won't merge until both of you approve.

All, from now on, let's write our blog posts (if involving code/data) in this.

Trello card here: https://trello.com/c/ylQ3VVdJ/246-make-blog-template-for-rmarkdown

### CODE REVIEW

**Comment by joebrew** [comment]
@xingcbrew Thanks for flagging this. I've made a few minor improvements. You can test to see how things will show up by opening `template.Rmd` in rstudio, knitting an html, and then opening that html in the browser. Can you confirm that this works okay for you?

@benmbrew Can you please review as well?

**Comment by xingcbrew** [comment]
Hey @joebrew,
Below is the error message I get when I open template.Rmd in rstudio and
knit as html. I couldn't find any answers online as to how to address this
issue. Have you encountered this before?

pandoc: Could not fetch https://fonts.googleapis.com/css?family=Lato:300,400,900
TlsExceptionHostPort (HandshakeFailed Error_EOF) "fonts.googleapis.com" 443
Error: pandoc document conversion failed with error 67
In addition: Warning message:
MathJax doesn't work with self_contained when not using the rmarkdown
"default" template.
Execution halted

**Comment by joebrew** [comment]
@xingcbrew Ok, I'll try to figure it out. In my court. Hold off on further review of this....

**Comment by joebrew** [comment]
@xingcbrew I'm actually going to decline this PR, since I've incorporated these changes into the other currently open one (new blog post).

**Pull request closed without merging**
