### PR TITLE
Feature/blog mixed unions

### PR DESCRIPTION
**Pull request by xingcbrew**
@joebrew @benmbrew  Please review my blog post on interracial marriages. 
Thanks!

### CODE REVIEW

**Comment by joebrew** [comment]
@xingcbrew I've just done a detailed read, looking for errors. And I found none. Great post, interesting to read, and really great visualizations too.

My only question - what's up with the images? The charts don't show up for me when I open this in chrome (for example `images/blog/mixed_unions/age.png`), even though that chart is definitely part of the commit.

Can you confirm that you are experiencing the same error, and fix?

**Comment by xingcbrew** [comment]
@joebrew Thanks for reviewing. I was able to see the images in my chrome without any problems but think I figured out the issue (missing a ".." before the "/" in the image url). I've changed them and they should work now for you too. I'll merge once you confirm. Bedankt!

**Comment by joebrew** [comment]
@xingcbrew Great. I can now see all the images.

One more requested change (feel free to disagree). It would be nice to standardize the plots so that they all have the same theme. How about using the `theme_databrew()` object from the `databrew` package.

In case you haven't used this, it should be pretty simple. Here's how to install, then use:

*Installation*
In R, run the following:
```
devtools::install_github('databrew/databrew')
```

*Using*
Here's some R code as an example of the theme object.

```
library(ggplot2)
library(databrew)

df <- data.frame(a = 1:10,
                 b = (1:10) ^2)

g <- 
  ggplot(data = df,
       aes(x = a,
           y = b)) +
  geom_line()

g
g +
  theme_databrew()

```

**Comment by xingcbrew** [comment]
@joebrew So... I accidentally deleted the R script that I used to make all the charts for this blog post on mixed unions the other day while moving it from one folder to another and putting the wrong file in the trash, which I've since emptied. I'm not too keen on writing a whole new script, so I'll have to go with these charts this time. I'll use the databrew theme for my next post :)

**Comment by joebrew** [comment]
@xingcbrew Okay. Understood. Great post!

**Pull request merged**
