### PR TITLE
Feature/251 blog post on gosd package

### PR DESCRIPTION
**Pull request by joebrew**
https://trello.com/c/DWeMOFTH/251-blog-post-on-gsod-package

### CODE REVIEW

**Comment by joebrew** [comment]
@xingcbrew I could really use your help on this one. I use `gsod.Rmd` to create `gsod.html`. But you'll note a few problems, specifically with the code chunks (they need to appear in a monospace font, and they need to all be left aligned). Do you know how I can tweak the `post_template.html` or any of the css to make that work correctly?

Sorry to dump this on you, but I've been banging my head against a wall with this and can't quite figure it out...

**Comment by xingcbrew** [comment]
@joebrew No problem, I'll give this a shot now :)

**Comment by xingcbrew** [comment]
@joebrew, Sorry, I've been looking at this for a long time and can't seem to figure out the issue...I'm not too familiar what rmarkdown in html and the gsod.html file is too large to open in my html text editor, so I can't preview it. 

One thing that I can see is that on the post_template.html, the top line is duplicated (though I doubt that's what is causing the problem). 

I'll do some more investigating on this issue.

**Comment by joebrew** [comment]
​Hey, yeah, focus your energies on post_template.html. That's where the fix
should be implemented (if one is possible)...​

**Comment by xingcbrew** [comment]
@joebrew, My guess is that the html page isn't being linked to the the css stylesheet page correctly since all the fonts are off... could something be wrong with this line:
 $for(css)$
          <link rel="stylesheet" href="$css$">
Otherwise, I'm at a loss... sorry!

**Comment by joebrew** [comment]
@xingcbrew Okay. I've given up (for now) on the .Rmd route for this. I've now taken the more manual route. I think this is ready to go. Back to you for review. 

Note that the post is at `posts/gsod.html` and the vignette is at `gsod.html`.

**Comment by xingcbrew** [comment]
@joebrew Great post! I'll continue to try and figure out how to make the .Rmd pages work with the HTML. 

One of the links wasn't working in your post, but I think I found the correct one (https://data.noaa.gov/dataset/dataset/global-surface-summary-of-the-day-gsod) and replaced it. I also changed "DataBrew" to "Databrew" (I think that's what we agreed on to use) and added a link to the post on the databrew.cc/blog page. 

Vignette looks good. 

Back to you to merge.

**Comment by joebrew** [comment]
@xingcbrew Awesome. Thanks for the thorough review / fixes. Merging.

**Pull request merged**
